package com.paises.persistence;

import java.sql.Connection;
import java.sql.DriverManager;

import java.sql.Statement;


public class GeneralCrud {
	 public static void  accion() {

		  String driver = "org.apache.derby.jdbc.EmbeddedDriver";
		     String dbName = "BdPaises";
		     String dbParam = "create=true"; //Si la base de datos no existe, se crear� una nueva
		     String dbschema= "schema=paises";
		     String dbuser= "user=paises";
		     String dbpass= "password=manager";
		    // String dbDirectory = "//localhost:1527/BdPaises";
		     String connectionURL = "jdbc:derby:"   +dbName + ";"+ dbParam;//+ ";"   + dbschema + ";" + dbuser+ ";" + dbpass;
	     
	     Connection conn = null;
	     try{
	       Class.forName(driver);
	     } catch(java.lang.ClassNotFoundException e) {
	       e.printStackTrace();
	     }
	     
	     try {
	    	
	    	 conn = DriverManager.getConnection(connectionURL);
	      
	       
	
	     Statement statement = conn.createStatement();
	    
	    	 
	    	statement.executeUpdate( "CREATE TABLE posiciones_ini(CODPAIS	VARCHAR(2), CODDIV	INTEGER, CODPOS	INTEGER, CODEQUI INTEGER)");
 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',1,1,69)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',1,2,70)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',1,3,71)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',1,4,72)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',1,5,73)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',1,6,74)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',1,7,75)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',1,8,76)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',1,9,77)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',1,10,78)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',1,11,79)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',1,12,80)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',1,13,81)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',1,14,82)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',1,15,83)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',1,16,84)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',1,17,85)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',1,18,86)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',1,19,87)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',1,20,88)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',2,1,89)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',2,2,90)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',2,3,91)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',2,4,92)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',2,5,93)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',2,6,94)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',2,7,95)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',2,8,96)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',2,9,97)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',2,10,98)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',2,11,99)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',2,12,100)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',2,13,101)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',2,14,102)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',2,15,103)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',2,16,104)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',2,17,105)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',2,18,106)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',2,19,107)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',2,20,108)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',3,1,109)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',3,2,110)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',3,3,111)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',3,4,112)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',3,5,113)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',3,6,114)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',3,7,115)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',3,8,116)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',3,9,117)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',3,10,118)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',3,11,119)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',3,12,120)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',3,13,121)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',3,14,122)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',3,15,123)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',3,16,124)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',3,17,409)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',3,18,411)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',3,19,414)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',3,20,421)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',1,1,149)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',1,2,150)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',1,3,151)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',1,4,152)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',1,5,153)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',1,6,154)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',1,7,155)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',1,8,156)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',1,9,157)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',1,10,158)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',1,11,159)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',1,12,160)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',1,13,161)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',1,14,162)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',1,15,163)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',1,16,164)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',1,17,165)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',1,18,166)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',1,19,167)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',1,20,168)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',2,1,169)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',2,2,170)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',2,3,171)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',2,4,172)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',2,5,173)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',2,6,174)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',2,7,175)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',2,8,176)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',2,9,177)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',2,10,178)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',2,11,179)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',2,12,180)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',2,13,181)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',2,14,182)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',2,15,183)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',2,16,184)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',2,17,185)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',2,18,186)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',2,19,187)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',2,20,188)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',2,21,189)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',2,22,190)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',3,1,191)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',3,2,192)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',3,3,193)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',3,4,194)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',3,5,195)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',3,6,196)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',3,7,197)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',3,8,198)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',3,9,199)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',3,10,200)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',3,11,201)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',3,12,202)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',3,13,203)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',3,14,204)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',3,15,205)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',3,16,206)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',3,17,207)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',3,18,208)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',3,19,209)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',3,20,210)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',4,1,211)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',4,2,212)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',4,3,213)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',4,4,214)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',4,5,215)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',4,6,216)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',4,7,217)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',4,8,218)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',4,9,219)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',4,10,220)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',4,11,221)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',4,12,222)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',4,13,223)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',4,14,224)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',4,15,225)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',4,16,226)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',4,17,227)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',4,18,228)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',4,19,229)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('ES',4,20,230)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',1,1,345)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',1,2,346)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',1,3,347)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',1,4,348)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',1,5,349)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',1,6,350)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',1,7,351)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',1,8,352)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',1,9,353)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',1,10,354)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',1,11,355)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',1,12,356)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',1,13,357)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',1,14,358)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',1,15,359)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',1,16,360)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',1,17,361)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',1,18,362)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',1,19,363)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',1,20,364)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',2,1,365)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',2,2,366)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',2,3,367)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',2,4,368)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',2,5,369)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',2,6,370)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',2,7,371)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',2,8,372)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',2,9,373)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',2,10,374)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',2,11,375)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',2,12,376)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',2,13,377)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',2,14,379)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',2,15,380)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',2,16,381)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',2,17,382)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',2,18,384)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',2,19,385)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',2,20,386)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',2,21,387)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',2,22,388)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',3,1,389)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',3,2,390)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',3,3,391)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',3,4,392)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',3,5,393)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',3,6,394)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',3,7,395)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',3,8,396)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',3,9,397)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',3,10,398)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',3,11,399)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',3,12,400)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',3,13,401)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',3,14,402)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',3,15,403)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',3,16,404)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',3,17,405)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',3,18,406)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',3,19,407)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',3,20,408)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',3,21,410)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',3,22,412)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',4,1,413)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',4,2,415)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',4,3,416)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',4,4,417)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',4,5,418)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',4,6,419)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',4,7,420)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',4,8,422)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',4,9,423)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',4,10,424)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',4,11,425)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',4,12,426)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',4,13,427)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',4,14,428)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',4,15,429)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',4,16,430)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',4,17,431)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',4,18,432)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',4,19,433)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',4,20,434)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',4,21,435)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IN',4,22,436)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',1,1,437)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',1,2,438)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',1,3,439)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',1,4,440)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',1,5,441)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',1,6,442)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',1,7,443)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',1,8,444)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',1,9,445)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',1,10,446)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',1,11,447)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',1,12,448)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',1,13,449)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',1,14,450)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',1,15,451)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',1,16,452)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',1,17,453)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',1,18,454)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',1,19,455)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',1,20,456)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',2,1,457)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',2,2,458)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',2,3,459)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',2,4,460)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',2,5,461)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',2,6,462)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',2,7,463)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',2,8,464)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',2,9,465)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',2,10,466)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',2,11,467)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',2,12,468)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',2,13,469)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',2,14,470)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',2,15,471)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',2,16,472)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',2,17,473)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',2,18,474)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',2,19,475)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',2,20,476)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',2,21,477)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',2,22,478)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',3,1,479)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',3,2,480)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',3,3,481)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',3,4,482)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',3,5,483)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',3,6,484)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',3,7,485)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',3,8,486)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',3,9,487)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',3,10,488)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',3,11,489)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',3,12,490)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',3,13,491)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',3,14,492)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',3,15,493)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',3,16,494)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',3,17,495)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',3,18,496)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',3,19,681)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',3,20,682)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',4,1,497)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',4,2,498)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',4,3,499)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',4,4,500)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',4,5,501)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',4,6,502)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',4,7,503)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',4,8,504)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',4,9,505)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',4,10,506)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',4,11,507)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',4,12,508)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',4,13,509)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',4,14,510)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',4,15,511)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',4,16,512)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',4,17,513)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',4,18,514)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',4,19,683)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('IT',4,20,684)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',4,1,685)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',4,2,686)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',4,3,687)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',4,4,688)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',4,5,689)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',4,6,690)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',4,7,691)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',4,8,692)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',4,9,693)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',4,10,694)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',4,11,695)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',4,12,696)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',4,13,697)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',4,14,698)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',4,15,699)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',4,16,700)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',4,17,701)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',4,18,702)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',4,19,703)"); 
	    	statement.executeUpdate("insert into posiciones_ini VALUES('DE',4,20,704)"); 


	   
	     System.out.println("fin ok ");
	    
	       
	     }  catch (Throwable e)  {
	       System.out.println("Error en la bd '" + dbName + "'");
	       e.printStackTrace();
	     } finally {
	       try { conn.close(); }
	       catch (Throwable t){}
	     }
		
	 }
}
